### PR TITLE
Migrate legacy character-class-validator

### PR DESCRIPTION
**Pull request by grancalavera**
## Description

Migrates the legacy version of character-class-validator
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] My change follows the style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have read the [contribution guidelines](../CONTRIBUTING.md)
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by grancalavera** [comment]
@gabrielmontagne

**Comment by gabrielmontagne** [comment]
thank you @grancalavera , this has been merged into the WIP  https://github.com/zambezi/d3-utils/commits/keyboard-component-works branch.  A PR with these changes will follow shortly.

**Comment by mstade** [comment]
@gabrielmontagne should we close this then?

**Comment by gabrielmontagne** [comment]
Yes. Thanks @mstade

**Comment by gabrielmontagne** [comment]
Tho, I'd rather leave this open.
It will be automatically closed and merged when the other branch gets merged.

**Comment by mstade** [comment]
Fair enough :o)

**Pull request merged**
